site_name: OVOS Technical Manual
site_url: https://openvoiceos.github.io/ovos-technical-manual
nav:
  - Home:
      - Introduction: index.md
  - Getting Started:
      - ovos-installer: 50-ovos_installer.md
      - Manual Install: 001-release_channels.md
  - RaspOVOS:
      - Tutorial: 51-install_raspovos.md
      - Default Skills: 54-skill-examples.md
      - Troubleshooting: 55-raspovos_troubleshooting.md
  - Language Support:
      - Translations: lang_support.md
      - GitLocalize Tutorial: gitlocalize_tutorial.md
  - Architecture:
      - Overview: 99-architecture-overview.md
      - Bus: 100-bus_service.md
      - Listener: 101-speech_service.md
      - Core: 102-core.md
      - Skills and Intents: 399-intents.md
      - Audio: 103-audio_service.md
      - GUI: 104-gui_service.md
      - Platform/Hardware Abstraction Layer: 340-PHAL.md
      - Plugin Manager: 300-plugin-manager.md
      - Configuration: 110-config.md
  - Intent Pipelines:
      - Overview: pipelines_overview.md
      - Adapt: adapt_pipeline.md
      - Padatious: padatious_pipeline.md
      - Model2Vec: m2v_pipeline.md
      - Converse: converse_pipeline.md
      - Stop: stop_pipeline.md
      - Persona: 153-persona_pipeline.md
      - Common Query: cq_pipeline.md
      - OCP: 631-OCP_pipeline.md
      - Fallback: fallback_pipeline.md
  - Transformers:
      - Audio: audio_transformers.md
      - Utterance: utterance_transformers.md
      - Intents: intent_transformers.md
      - Dialog: dialog_transformers.md
      - TTS: tts_transformers.md
  - AI Agents:
      - Personas: 150-personas.md
      - AI Transformers: 151-llm-transformers.md
      - Specialized Solvers: 150-advanced_solvers.md
      - Tools for Agents: tools.md
  - Self Hosting:
      - Persona Server: 202-persona_server.md
      - HiveMind: 152-hivemind-agents.md
      - STT Server: 200-stt_server.md
      - TTS Server: 201-tts_server.md
      - Translate Server: 203-translate_server.md
  - Skill Development:
      - Design Guidelines: 400-skill-design-guidelines.md
      - Anatomy: 401-skill_structure.md
      - Dialog: 402-statements.md
      - Intent Design: 403-intents.md
      - Customization: 405-customization.md
      - Bus Interaction: 406-messagebus.md
      - Filesystem: 407-skill_filesystem.md
      - Skill Settings: 408-skill_settings.md
      - Skill API: 409-skill_api.md
      - Runtime Requirements: 410-skill_runtime_requirements.md
      - Skill Json: 411-skill_json.md
      - SSML: 420-ssml.md
      - F.A.Q.: 430-skill_dev_faq.md
  - Continuous Conversation:
      - Prompts: 500-prompts.md
      - Follow up Questions: 501-context.md
      - Converse: 502-converse.md
      - Intent Layers: 503-layers.md
      - Session Aware Skills: 504-session.md
  - Advanced Skill Types:
      - Fallback Skills: 600-fallbacks.md
      - Common Query Skills: 610-common_query.md
      - Media Skills: 630-OCP_skills.md
      - Universal Skills: 620-universal_skills.md
  - GUI:
      - Homescreen: 700-homescreen.md
      - Protocol: 701-gui_protocol.md
      - Shell: 702-ovos-shell.md
      - QT5 mycroft-gui: 710-qt5-gui.md
      - Plasma Bigscreen: 999-ovos_bigscreen.md
  - Voice Apps:
      - Standalone Apps: 590-voice_apps.md
      - QT Voice Apps: 711-qt_voice_apps.md
  - MessageBus:
      - Messagebus Client: 900-bus_client.md
      - GUI Interface: 720-skill_gui.md
      - Enclosure Api: 800-mk1_api.md
  - Plugin Development:
      - Microphone: 310-mic_plugins.md
      - Voice Activity Detection: 311-vad_plugins.md
      - Wake Word: 312-wake_word_plugins.md
      - Speech To Text: 313-stt_plugins.md
      - Text To Speech: 320-tts_plugins.md
      - Grapheme to Phoneme: 321-g2p_plugins.md
      - Transformers: 330-transformer_plugins.md
      - Language Detection/Translation: 350-translation_plugins.md
      - OCP Stream Extractors: 370-ocp_plugins.md
      - Media Playback: 371-media_plugins.md
  - Misc. Utilities:
      - Number Parser: 891-number_parser.md
      - Date Parser: 890-date_parser.md
      - Color Parser: 893-color_parser.md
      - Quebra Frases: 910-quebra_frases.md
      - Padacioso: 920-padacioso.md
      - Mark1 Utils: 801-mk1_utils.md
  - Misc. Information:
      - License: 002-license.md
      - Timeline: 003-timeline.md
theme: readthedocs
extra_css:
  - css/extra.css
