site_name: OVOS Technical Manual
site_url: https://openvoiceos.github.io/ovos-technical-manual
nav:
    - Home:
        - Introduction: index.md
        - Community: community.md
        - Timeline: timeline.md
        - License: license.md
    - Architecture:
        - Bus: bus_service.md
        - Core: core.md
        - Listener: speech_service.md
        - Audio: audio_service.md
        - GUI: gui_service.md
        - Configuration: config.md
    - Plugins:
        - Plugin Manager: OPM.md
        - Speech To Text: stt_plugins.md
        - Text To Speech: tts_plugins.md
        - Wake Word: ww_plugins.md
        - Voice Activity Detection: vad_plugins.md
        - Language Detection/Translation: lang_plugins.md
        - Question Solvers: solvers.md
        - Platform/Hardware Abstraction Layer: PHAL.md
        - Grapheme to Phoneme: g2p_plugins.md
        - Audio Playback: audio_plugins.md
    - Self Hosting:
        - STT Server: stt_server.md
        - TTS Server: tts_server.md
        - Translate Server: translate_server.md
    - Skills:
        - Design Guidelines: guidelines.md
        - Anatomy: skill_structure.md
        - Dialog: statements.md
        - Prompts: prompts.md
        - Intents: intents.md
        - Context: context.md
        - Converse: converse.md
        - Filesystem: skill_filesystem.md
        - Skill Settings: skill_settings.md
        - Skill GUI: skill_gui.md
        - Skill API: skill_api.md
        - Skill Json: skill_json.md
        - Skill Tests: skill_tests.md
        - F.A.Q.: dev.md
    - GUI:
        - Protocol: gui_protocol.md
        - Shell: shell.md
        - QT5 mycroft-gui: qt5.md
    - Backend:
        - Available Backends: backend.md
        - Backend Client: backend_client.md
        - Personal Backend: personal_backend.md
        - Backend Manager: backend_manager.md
    - Technologies:
        - Common Play: OCP.md
        - Padacioso: padacioso.md
        - Jurebes: jurebes.md

theme: readthedocs
extra_css:
    - css/extra.css
